### PR TITLE
Imported general documentation

### PR DESCRIPTION
**Pull request by nathmo**
Added the information available in the old README
fixed some spelling mistake (some may still be present. I'm really not good with that kind of stuff and so are most spell checker...)
updated the index

(I'm sorry I merged all my branch as I didn't manage to rename them and navigating between page became hell. Result : This massive PR) but if you find some local mistake tell me and I will add a commit.

### CODE REVIEW

**Comment by kuklinistvan** [comment]
I'll check back later, hold on ;)

**Comment by kuklinistvan** [comment]
Thank you! Please install `mkdocs` and `mkdocs-material` to your computer ([here's how to do it](https://squidfunk.github.io/mkdocs-material/getting-started/)) and run `mkdocs serve` to preview your changes on [localhost](http://127.0.0.1:8000/).

Right now it looks like this:

image

**Comment by kuklinistvan** [comment]
Also: I don't want to move _everything_ to the Wiki. I want to keep in the repository what is technical (such as version, testing, Docker link, etc.), and in the wiki what is for inexperienced users and other good-to-knows.

But I like your description on creating Docker images for different architectures :)

**Comment by nathmo** [comment]
Sorry I expected Mkdocs to just work out of the box I will do as you said
(I will try to remove the testing.md and such too technical stuff)

**Comment by nathmo** [comment]
it's fixed. I did'nt removed the part that is too technical as i don't know want you want exactly so i will let you do it if you dont mind

**Comment by kuklinistvan** [comment]
Okay, give me some time and I'll review it

**Comment by nathmo** [comment]
Any update ?

**Comment by kuklinistvan** [comment]
I'm working on it in this very minute. I've sent you a message on Gitter.

**Comment by kuklinistvan** [comment]
I've updated the portal based on your PR.
https://ankicommunity.github.io/

**Comment by nathmo** [comment]
It look really nice ^^ thanks

**Pull request closed without merging**
